include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    camel_case_types: false
    non_constant_identifier_names: false
    library_prefixes: false
    sized_box_for_whitespace: false
    always_put_control_body_on_new_line: false
    avoid_print: false
    use_build_context_synchronously: false
    prefer_final_fields: false
    unnecessary_brace_in_string_interps: false
    avoid_unnecessary_containers: false
    await_only_futures: false
    prefer_const_literals_to_create_immutables: false
    file_names: false
    always_declare_return_types: false
    annotate_overrides: false
    unnecessary_overrides: false
    prefer_final_locals: false
    use_key_in_widget_constructors: false
    sort_child_properties_last: false
    prefer_interpolation_to_compose_strings: false
    prefer_typing_uninitialized_variables: false
    prefer_single_quotes: false
    implementation_imports: false
    avoid_private_typedef_functions: false
    no_leading_underscores_for_local_identifiers: false


analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    invalid_annotation_target: ignore
